### ISSUE TITLE
[RFC] Stop tests on push

### ISSUE THREAD

**Issue by RitikJaiswal75** [RealDevSquad/mobile-app#137]
## Issue
- When a PR is created, the git workflow runs tests on all the pull requests, but once the tests are run on pull requests they run again during push

### When was the issue discovered?
- The issue was discovered on 18th August 2022 during a hangout call while trying to merge PRs.

### Files that might be creating this
- `.github/workflows/test.yml`

### Screenshot of the Problem
![image](https://user-images.githubusercontent.com/57758447/185927191-4f7245d6-44b9-46a7-a355-b49ec54ef8b8.png)

**Comment by pranikz** [comment]
I can pick this issue .
ETA:  2nd October

**Comment by shreya-mishra** [comment]
Will you please mention the ETA too ?

**Comment by pranikz** [comment]
Hello @RitikJaiswal75 
I have explored in the repo and found out the CI/ CD operations are happening here on PRs not on push and afaik the issue was It was running on Push too , seems the problem is solved in the case of  mobile-app repo, If it is happening here can you just point out where it is happening on push?
![image](https://user-images.githubusercontent.com/44764138/192820852-4520e78e-141f-4829-a5fe-e05b3fef161e.png)

CC : @shreya-mishra

**Comment by RitikJaiswal75** [comment]
it is still present in codeql.yml 
![image](https://user-images.githubusercontent.com/57758447/195105133-7b58109c-1da4-4e3e-b370-05124d9f6a06.png)

**Comment by RitikJaiswal75** [comment]
CodeQl YML runs both on push and pull. Is it necessary and if yes why?
